apiVersion: apps/v1
kind: Deployment
metadata:
  name: module1-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: module1-service
  template:
    metadata:
      labels:
        app: module1-service
    spec:
      hostAliases:
      - ip: "10.60.3.27"
        hostnames:
        - "hl22.zil"
      - ip: "10.60.3.28"
        hostnames:
        - "hl23.zil"
      imagePullSecrets:
        - name: regcred
      containers:
        - name: module1-service
          image: kidawr/module1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: db-credentials
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resizePolicy:
            - resourceName: cpu
              restartPolicy: RestartContainer
            - resourceName: memory
              restartPolicy: NotRequired # Default, but explicit here
          resources:
            requests:
              cpu: "800m"
              memory: "1024Mi"
            limits:
              cpu: "2"
              memory: "1024Mi"
