version: '3.8'
# docker ps
# docker logs spring-boot-app 
# docker build -t kedawr/module1 -f . пересобрать rvx
#  docker build -t kidawr/module1  .  && docker compose down && docker compose up -d && docker exec -it spring-boot-app /bin/bash
services:
  app:
    image: kidawr/module1
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: spring-boot-app
    restart: always
    #depends_on:
    #  - database
    env_file:
      - .env
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Автоматическое обновление схемы базы данных
      SPRING_JPA_SHOW_SQL: 'false'  # отключаем логи Hibernate
      SERVER_TOMCAT_MAX_THREADS: '200'
    ports:
      - "8080:8080"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'  # лимиты для CPU
          memory: 512M  # лимиты для памяти
        reservations:
          cpus: '0.5'  # Резервирование CPU
          memory: 256M  # Резервирование памяти

  additional-service:
    #build:
    #  context: ../additional-service
    #  dockerfile: Dockerfile
    image: kidawr/additional-service
    container_name: additional-service
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.5'  # лимиты для CPU
          memory: 512M  # лимиты для памяти
        reservations:
          cpus: '0.5'  # Резервирование CPU
          memory: 256M  # Резервирование памяти
    environment:
      CORE_SERVICE_HOST: ${CORE_SERVICE_HOST:-spring-boot-app}
      CORE_SERVICE_PORT: ${CORE_SERVICE_PORT:-8080}
          
networks:
  app-network:
    driver: bridge
