apiVersion: apps/v1
kind: Deployment
metadata:
  name: additional-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: additional-service
  template:
    metadata:
      labels:
        app: additional-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: hl16.zil
      imagePullSecrets:
        - name: regcred
      containers:
        - name: additional
          image: kidawr/additional-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: config

          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            periodSeconds: 10 # Проверка каждый 10 секунд
            timeoutSeconds: 3 # Таймаут запроса 3 секунды
            failureThreshold: 9 # Количество неудачных попыток перед пометкой контейнера как неготового


          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 9

          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"
