apiVersion: v1
kind: Service
metadata:
  name: module1-service-nodeport
spec:
  type: NodePort
  selector:
    app: module1-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080